spring:
  application:
    name: BiddingSystem
  # Persistence configurations ----------------------------------------------------
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  # Datasource connections  -------------------------------------------------------
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/sample
    username: root
    password: QWEqwe123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Freemarker configuration -------------------------------------------------------
  freemarker:
    charset: utf-8
    template-loader-path: classpath:/templates
    suffix: .ftl
  web:
    resources:
      static-locations: classpath:/static
  # Spring Security OAuth2 config --------------------------------------------------
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  # Spring doc and swagger config --------------------------------------------------
openapi:
  service:
    title: price-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://${ENDPOINTS_HOST:localhost}:${ENDPOINTS_PORT:8080} #api gateway url
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    #  http://localhost:8080/swagger-ui/index.html
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    #    Selection dropdown definitions
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        display-name: API Gateway Service
